### ISSUE TITLE
Cannot use H2

### ISSUE THREAD

**Issue by frederic-gendebien** [dnvriend/akka-persistence-jdbc#116]
GIVEN a project which I just want to use H2 for
WHEN I copy the the content of the configuration you give as an example "h2-application.conf" into my application.conf
THEN I have this issue:
...
Caused by: java.lang.RuntimeException: Failed to load class of driverClassName org.postgresql.Driver
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:323)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.$anonfun$forConfig$3(HikariCPJdbcDataSource.scala:35)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.$anonfun$forConfig$3$adapted(HikariCPJdbcDataSource.scala:35)
	at scala.Option.map(Option.scala:146)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:35)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource$.forConfig(HikariCPJdbcDataSource.scala:25)
	at slick.jdbc.JdbcDataSource$.forConfig(JdbcDataSource.scala:48)
	at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig(JdbcBackend.scala:288)
	at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forConfig$(JdbcBackend.scala:285)
	at slick.jdbc.JdbcBackend$$anon$3.forConfig(JdbcBackend.scala:33)
	at akka.persistence.jdbc.util.SlickDatabase$.$anonfun$forConfig$4(SlickDriver.scala:36)
	at scala.Option.getOrElse(Option.scala:121)
	at akka.persistence.jdbc.util.SlickDatabase$.forConfig(SlickDriver.scala:36)
	at akka.persistence.jdbc.journal.JdbcAsyncWriteJournal.<init>(JdbcAsyncWriteJournal.scala:42)
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.postgresql.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:318)
	... 29 more

REMARKS Indeed I don t have Postgresql in my class path because I don t want it!
QUESTION How should I configure it so that Postgresql default behaviour is totally overwritten?

**Comment by WellingR** [comment]
It is hard to help you without seeing your actual config. There are several things you should note:

- First of all make sure there is absolutely no reference to 'org.postgresql.Driver' in your code.
- If some configuration values are missing then the reference.conf file from akka-persistence-jdbc will be used. Which uses the postgres driver by default.

Anyhow I am pretty sure there is still some reference to the postgres driver in your (resolved) config.
Please refer to https://github.com/typesafehub/config#debugging-your-configuration which can help you with displaying the actual configuration being used.

If all of this does not help, then I would need to have a look at the configuration files to help you out.

**Comment by frederic-gendebien** [comment]
Thanks for your answer!

In my code I have no reference to postgresql, and here is the configuration:

akka {
  loglevel = "DEBUG"

  actor {
    serialize-messages = off
    serialize-creators = off

    serializers {
...
    }

    serialization-bindings {
...    
   }
  }

  persistence {
    journal {
      plugin = "jdbc-journal"
      auto-start-journals = ["jdbc-journal"]
    }

    snapshot-store {
      plugin = "jdbc-snapshot-store"
      auto-start-snapshot-stores = ["jdbc-snapshot-store"]
    }

    //    circuit-breaker {
    //      max-failures = 10
    //      call-timeout = 40s
    //      reset-timeout = 60s
    //    }
  }

  jdbc-journal {
    slick = ${slick}

  }

  # the akka-persistence-snapshot-store in use
  jdbc-snapshot-store {
    slick = ${slick}
  }

  # the akka-persistence-query provider in use
  jdbc-read-journal {
    refresh-interval = "10ms"

    max-buffer-size = "500"

    slick = ${slick}
  }

  slick {
    driver = "slick.driver.H2Driver$"
    db {
      url = "jdbc:h2:mem:test-database;DATABASE_TO_UPPER=false;"
      user = "root"
      password = "root"
      driver = "org.h2.Driver"
      connectionTestQuery = "SELECT 1"
      host = "mescouilles"

      numThreads = 20
      maxConnections = 100
      minConnections = 1
      connectionTimeout = 1800000 // 30 minutes
    }
  }
}

**Comment by frederic-gendebien** [comment]
ok... My bad, wrong hierarchy

**Comment by siniconcur** [comment]
I have the same issue when using acca with scala and the config for h2db. The config for persistence look exactly like the one mentioned above.
what does wrong hierarchy mentioned above mean? I have the config in application.conf under src/main/resources

**Comment by WellingR** [comment]
I cannot see exactly what is wrong for your case. However please have a look at the example config.

https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/test/resources/h2-application.conf

You could use that file as a base and make the changes that you need

**Comment by siniconcur** [comment]
Hi, Thanks a lot for your quick response.
I had the jdbc-journal and    jdbc-snapshot-store under the akka{} hierarchy.
I have now put them outside of the akka hierarchy in application.conf and I got further.

But I get the table not found exception now. Could be coz I am not creating the tables in the application myself. Do I need to do that? Can you please share an eg of how to do that?

Below is the error related to table not found.
org.h2.jdbc.JdbcSQLException: Table "snapshot" not found; SQL statement:
select "persistence_id", "sequence_number", "created", "snapshot" from "snapshot" where "persistence_id" = ? order by "sequence_number" desc limit 1 [42102-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5388)
	at org.h2.command.Parser.readTableFilter(Parser.java:1257)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:1896)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2044)
	at org.h2.command.Parser.parseSelectSub(Parser.java:1890)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1711)
	at org.h2.command.Parser.parseSelect(Parser.java:1699)
	at org.h2.command.Parser.parsePrepared(Parser.java:445)
	at org.h2.command.Parser.parse(Parser.java:317)
	at org.h2.command.Parser.parse(Parser.java:289)
	at org.h2.command.Parser.prepareCommand(Parser.java:254)
	at org.h2.engine.Session.prepareLocal(Session.java:560)
	at org.h2.engine.Session.prepareCommand(Session.java:501)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1202)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:290)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:310)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement(JdbcBackend.scala:321)
	at slick.jdbc.JdbcBackend$SessionDef.prepareStatement$(JdbcBackend.scala:311)
	at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:433)
	at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:32)
	at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:21)
	at slick.jdbc.Invoker.foreach(Invoker.scala:47)
	at slick.jdbc.Invoker.foreach$(Invoker.scala:46)
	at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:15)
	at slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
	at slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:215)
	at slick.jdbc.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:215)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:242)
	at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by janjaali** [comment]
Unlike the (cassandra-plugin, as far as I know they did this initially) this plugin does not initialise the tables for you. Have a look at: [H2Schema](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/test/resources/schema/h2/h2-schema.sql)
