### ISSUE TITLE
java.lang.NoSuchMethodError: slick.lifted.Shape$.mappedProjectionShape()Lslick/lifted/Shape;

### ISSUE THREAD

**Issue by anant1525** [dnvriend/akka-persistence-jdbc#147]
Hi, 
I am using the plugin for akka persistence using mysql database.
After the doing the mentioned configuration getting the below error which looks to me related with versions need advice.

using scala 2.12
slick 2.12

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Uncaught error from thread [example-akka.persistence.dispatchers.default-plugin-dispatcher-6]: slick.lifted.Shape$.mappedProjectionShape()Lslick/lifted/Shape;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[example]
java.lang.NoSuchMethodError: slick.lifted.Shape$.mappedProjectionShape()Lslick/lifted/Shape;
	at akka.persistence.jdbc.snapshot.dao.SnapshotTables$Snapshot.$times(SnapshotTables.scala:40)
	at slick.lifted.AbstractTable.toNode(AbstractTable.scala:43)
	at slick.lifted.RepShape$.toNode(Shape.scala:111)
	at slick.lifted.RepShape$.toNode(Shape.scala:103)
	at slick.lifted.ShapedValue.toNode(Shape.scala:273)
	at slick.lifted.TableQuery.toNode$lzycompute(Query.scala:301)
	at slick.lifted.TableQuery.toNode(Query.scala:301)
	at slick.lifted.Query.filterHelper(Query.scala:47)
	at slick.lifted.Query.withFilter(Query.scala:60)
	at slick.lifted.Query.filter(Query.scala:53)
	at akka.persistence.jdbc.snapshot.dao.SnapshotQueries._selectAll(SnapshotQueries.scala:32)
	at akka.persistence.jdbc.snapshot.dao.SnapshotQueries._selectByPersistenceIdAndMaxSeqNr(SnapshotQueries.scala:36)
	at akka.persistence.jdbc.snapshot.dao.SnapshotQueries.$anonfun$selectByPersistenceIdAndMaxSeqNr$1(SnapshotQueries.scala:37)
	at slick.lifted.CompiledFunction.toNode(Compiled.scala:60)
	at slick.lifted.CompilersMixin.compiledQuery(Compiled.scala:47)
	at slick.lifted.CompilersMixin.compiledQuery$(Compiled.scala:47)
	at slick.lifted.CompiledFunction.compiledQuery$lzycompute(Compiled.scala:53)
	at slick.lifted.CompiledFunction.compiledQuery(Compiled.scala:53)
	at slick.lifted.AppliedCompiledFunction.compiledQuery(Compiled.scala:81)
	at slick.basic.BasicProfile$API.streamableAppliedCompiledFunctionActionExtensionMethods(BasicProfile.scala:66)
	at slick.basic.BasicProfile$API.streamableAppliedCompiledFunctionActionExtensionMethods$(BasicProfile.scala:65)
	at slick.jdbc.JdbcProfile$$anon$1.streamableAppliedCompiledFunctionActionExtensionMethods(JdbcProfile.scala:67)
	at akka.persistence.jdbc.snapshot.dao.ByteArraySnapshotDao.snapshotForMaxSequenceNr(ByteArraySnapshotDao.scala:44)
	at akka.persistence.jdbc.snapshot.JdbcSnapshotStore.loadAsync(JdbcSnapshotStore.scala:75)
	at akka.persistence.snapshot.SnapshotStore$$anonfun$receiveSnapshotStore$1.$anonfun$applyOrElse$1(SnapshotStore.scala:37)
	at akka.pattern.CircuitBreaker$State.materialize$1(CircuitBreaker.scala:685)
	at akka.pattern.CircuitBreaker$State.callThrough(CircuitBreaker.scala:722)
	at akka.pattern.CircuitBreaker$State.callThrough$(CircuitBreaker.scala:683)
	at akka.pattern.CircuitBreaker$Closed$.callThrough(CircuitBreaker.scala:794)
	at akka.pattern.CircuitBreaker$Closed$.invoke(CircuitBreaker.scala:803)
	at akka.pattern.CircuitBreaker.withCircuitBreaker(CircuitBreaker.scala:199)
	at akka.persistence.snapshot.SnapshotStore$$anonfun$receiveSnapshotStore$1.applyOrElse(SnapshotStore.scala:37)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at akka.persistence.jdbc.snapshot.JdbcSnapshotStore.aroundReceive(JdbcSnapshotStore.scala:42)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by WellingR** [comment]
Most likely you are getting this issue because you do not use the same slick version as akka-persistence-jdbc uses.

What version of slick are you using (your issue report states 2.12 but that is the scala version). Also, what version of akka-persistence-jdbc are you using?

**Comment by anant1525** [comment]
Hi WellingR,

I am using "akka-persistence-jdbc_2.12" version 3.0.0

One More thing our original Akka implementation using scala version 2.11 so i have to switch to that.

I appreciate your help, much needed for.

Best Regards

**Comment by WellingR** [comment]
All dependencies should have the scala-binary versions alligned.

If you use scala 2.11.x use only _2.11 dependencies. In case of scala 2.12.x use only _2.12 dependencies. Never mix these, since this will cause issues.

**Comment by WellingR** [comment]
By the way are you using sbt or maven?

**Comment by anant1525** [comment]
Hi Welling,

Yes I am using now _2.11 across all. And I am using maven.

attaching my pom.xml for better view.
[pom.zip](https://github.com/dnvriend/akka-persistence-jdbc/files/1487049/pom.zip)


Best Regards,

**Comment by WellingR** [comment]
You should allign your slick version with the slick version that is used by akka-persistence-jdbc. In this case that means you should use 

```xml
<dependency>
    <groupId>com.typesafe.slick</groupId>
    <artifactId>slick_2.11</artifactId>
    <version>3.2.1</version>
</dependency>
```

Let me know if this resolves your issue

**Comment by WellingR** [comment]
@anant1525 Has your problem been resolved? If so you may close this issue

**Comment by anant1525** [comment]
Hi WellingR,
Not yet I as I was trying with akka 2.3, but I will update soon on this thread. As resumed the work with akka 2.5, I will update soon.

**Comment by anant1525** [comment]
Hi WellingerR,

plugin is working fine with mariadb 10.2,  akka 2.5.4, scala 2.12.  
![akka-snapshot](https://user-images.githubusercontent.com/33789263/33240294-fac9ba9a-d2d9-11e7-96bd-2d9cf24a1c67.PNG)
![akka-journal](https://user-images.githubusercontent.com/33789263/33240295-faf26602-d2d9-11e7-89e7-f7af0c320ab3.PNG)

Many thanks for all the support over the period... really appreciate this ...  :)

**Comment by WellingR** [comment]
Good to hear you have it all working now. I am closing this issue.
