### ISSUE TITLE
Cannot create multiple instances of the read journal

### ISSUE THREAD

**Issue by TimMoore** [dnvriend/akka-persistence-jdbc#169]
`JdbcReadJournal` starts an actor when a query for events by tag is issued:

https://github.com/dnvriend/akka-persistence-jdbc/blob/ca058d607fae67758bce37c9d1b1002114b9f2f0/src/main/scala/akka/persistence/jdbc/query/scaladsl/JdbcReadJournal.scala#L95-L96

Akka Persistence allows for the creation of multiple instances of a read journal, with different configuration paths. Because the `JournalSequenceActor` is created with a hardcoded name, as a top-level actor, this causes a conflict when there is more than one JDBC read journal created:

```
[error] akka.actor.RepointableActorRef [sourceThread=engage-employee-service-application-akka.actor.default-dispatcher-18, akkaTimestamp=18:46:12.462UTC, akkaSource=akka://engage-employee-service-application/user/StreamSupervisor-1/flow-8-0-ignoreSink, sourceActorSystem=engage-employee-service-application] - Error in stage [akka.stream.impl.UnfoldAsync@440425b8]: actor name akka-persistence-jdbc-journal-sequence-actor] is not unique!
akka.actor.InvalidActorNameException: actor name [akka-persistence-jdbc-journal-sequence-actor] is not unique!
at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)
at akka.actor.dungeon.Children.reserveChild(Children.scala:134)
at akka.actor.dungeon.Children.reserveChild$(Children.scala:132)
at akka.actor.ActorCell.reserveChild(ActorCell.scala:370)
at akka.actor.dungeon.Children.makeChild(Children.scala:272)
at akka.actor.dungeon.Children.attachChild(Children.scala:48)
at akka.actor.dungeon.Children.attachChild$(Children.scala:47)
at akka.actor.ActorCell.attachChild(ActorCell.scala:370)
at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:718)
at akka.persistence.jdbc.query.scaladsl.JdbcReadJournal.journalSequenceActor$lzycompute(JdbcReadJournal.scala:97)
at akka.persistence.jdbc.query.scaladsl.JdbcReadJournal.journalSequenceActor(JdbcReadJournal.scala:95)
at akka.persistence.jdbc.query.scaladsl.JdbcReadJournal.retrieveNextBatch$1(JdbcReadJournal.scala:196)
at akka.persistence.jdbc.query.scaladsl.JdbcReadJournal.$anonfun$eventsByTag$1(JdbcReadJournal.scala:228)
```

The `ReadJournalProvider` implementation can take the config path as an optional third parameter, which can be used to namespace the actor name.

**Comment by WellingR** [comment]
Good find, I did not know it was possible to create multiple instances. We should definitely include a test for this scenario
