### ISSUE TITLE
Using explicit db settings config, startup fails due to no jndiName specified

### ISSUE THREAD

**Issue by hairylime** [dnvriend/akka-persistence-jdbc#185]
Here are the relevant parts of my config:
```akka {
... remove unrelated akka config
  persistence {
    journal {
      plugin = "jdbc-journal"
      // Enable the line below to automatically start the journal when the actorsystem is started
       auto-start-journals = ["jdbc-journal"]
    }
    snapshot-store {
      plugin = "jdbc-snapshot-store"
      // Enable the line below to automatically start the snapshot-store when the actorsystem is started
      auto-start-snapshot-stores = ["jdbc-snapshot-store"]
    }
  }
}

jdbc-journal {
  slick = ${slick}
}

# the akka-persistence-snapshot-store in use
jdbc-snapshot-store {
  slick = ${slick}
}

# the akka-persistence-query provider in use
jdbc-read-journal {
  slick = ${slick}
}

slick {
  profile = "slick.jdbc.PostgresProfile$"
  db {
    host = localhost
    host = ${?POSTGRES_HOST}

    port = 21212
    port = ${?POSTGRES_PORT}

    dbname = adbname
    dbname = ${?POSTGRES_DB}

    user = "auser"
    user = ${?POSTGRES_USER}

    password = "apassword!"
    password = ${?POSTGRES_PASSWORD}

    maxconnections = 30
    maxconnections = ${?DB_MAXCONNECTIONS}

    domigration = true
    maxconnections = ${?DB_DOMIGRATION}

    auxflywaylocations = ""
    auxflywaylocations = ${?AUX_FLYWAY}

    initTimeout = 300s
    initTimeout = ${?DB_INIT_TIMEOUT}

    driver = "org.postgresql.Driver"

    url = "jdbc:postgresql://"${slick.db.host}":"${slick.db.port}"/"${slick.db.dbname}
    url = ${?JDBC_URL}

    numThreads = 5
  }
}
```
When I run with this, I get 
```11:36:02.262 TKD [xmplr-app-akka.persistence.dispatchers.default-plugin-dispatcher-6] DEBUG com.zaxxer.hikari.HikariConfig - Driver class org.postgresql.Driver found in Thread context class loader sun.misc.Launcher$AppClassLoader@677327b6
11:36:02.271 TKD [xmplr-app-akka.actor.default-dispatcher-3] ERROR akka.actor.OneForOneStrategy - Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
akka.actor.ActorInitializationException: akka://xmplr-app/system/jdbc-journal: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:193)
	at akka.actor.ActorCell.create(ActorCell.scala:669)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:66)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:624)
	at akka.actor.ActorCell.create(ActorCell.scala:650)
	... 7 common frames omitted
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:350)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forName(JdbcBackend.scala:114)
	at slick.jdbc.JdbcBackend$DatabaseFactoryDef.forName$(JdbcBackend.scala:113)
	at slick.jdbc.JdbcBackend$$anon$3.forName(JdbcBackend.scala:32)
	at akka.persistence.jdbc.util.SlickDatabase$.$anonfun$forConfig$1(SlickDriver.scala:34)
	at scala.Option.map(Option.scala:146)
	at akka.persistence.jdbc.util.SlickDatabase$.forConfig(SlickDriver.scala:34)
	at akka.persistence.jdbc.journal.JdbcAsyncWriteJournal.<init>(JdbcAsyncWriteJournal.scala:48)
	... 16 common frames omitted
```

Which is coming from where it first tries to resolve via JNDI...

**Comment by hairylime** [comment]
nvm - problem on my side
