### ISSUE TITLE
ClassCastException while replaying events

### ISSUE THREAD

**Issue by elkorn** [dnvriend/akka-persistence-jdbc#33]
It's me again. :)

This time I'm having an issue after storing some events in the DB and restarting the application, thus causing the actor to update its state with replayed events.

The startup seems to go well:

```
[DEBUG] [02/23/2016 19:03:59.467] [run-main-0] [EventStream(akka://default)] Default Loggers started
[DEBUG] [02/23/2016 19:03:59.543] [default-akka.actor.default-dispatcher-3] [PersistenceQuery(akka://default)] Create plugin: jdbc-read-journal akka.persistence.jdbc.query.journal.JdbcReadJournalProvider
[DEBUG] [02/23/2016 19:03:59.566] [default-akka.actor.default-dispatcher-4] [akka.persistence.Persistence(akka://default)] Create plugin: jdbc-journal akka.persistence.jdbc.journal.JdbcAsyncWriteJournal
[DEBUG] [02/23/2016 19:03:59.657] [default-akka.actor.default-dispatcher-4] [akka.persistence.Persistence(akka://default)] Create plugin: jdbc-snapshot-store akka.persistence.jdbc.snapshot.JdbcSnapshotStore
[DEBUG] [02/23/2016 19:03:59.690] [default-akka.actor.default-dispatcher-3] [AkkaPersistenceConfigImpl(akka://default)] 
 ====================================
 Akka Persistence JDBC Configuration:
 ====================================
 SlickConfiguration(slick.driver.PostgresDriver,None)
 ====================================
 PersistenceQueryConfiguration(,)
 ====================================
 JournalTableConfiguration(journal,None,JournalTableColumnNames(persistence_id,sequence_number,created,tags,message))
 ====================================
 DeletedToTableConfiguration(deleted_to,None,DeletedToTableColumnNames(persistence_id,deleted_to))
 ====================================
 SnapshotTableConfiguration(snapshot,None,SnapshotTableColumnNames(persistence_id,sequence_number,created,snapshot))
 ====================================
    
[DEBUG] [02/23/2016 19:03:59.734] [run-main-0] [AkkaSSLConfig(akka://default)] Initializing AkkaSSLConfig extension...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[DEBUG] [02/23/2016 19:03:59.980] [run-main-0] [AkkaSSLConfig(akka://default)] buildHostnameVerifier: created hostname verifier: com.typesafe.sslconfig.ssl.DefaultHostnameVerifier@5c271025
[DEBUG] [02/23/2016 19:04:01.976] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/0] Successfully bound to /0:0:0:0:0:0:0:0:9000
[DEBUG] [02/23/2016 19:04:02.417] [default-akka.actor.default-dispatcher-4] [akka.serialization.Serialization(akka://default)] Using serializer[akka.persistence.serialization.MessageSerializer] for message [akka.persistence.PersistentRepr]
```

Then the problem appears:
```
[ERROR] [02/23/2016 19:04:02.492] [default-akka.actor.default-dispatcher-3] [akka://default/user/$a] Persistence failure when replaying events for persistenceId [Counter]. Last known sequence number [19]
java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to akka.Done
	at akka.persistence.jdbc.journal.SlickAsyncWriteJournal$$anonfun$asyncReplayMessages$2.apply(SlickAsyncWriteJournal.scala:88)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236)
	at scala.util.Try$.apply(Try.scala:191)
	at scala.util.Success.map(Try.scala:236)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The write actor:
```scala
object CounterActor {
  case class Increment(value: Int) extends Command
  case class Incremented(value: Int) extends Event

  case class IncrementState(value: Int = 0) {
    def updated(event: Incremented): IncrementState = copy(event.value + value)
  }
}


class CounterActor extends PersistentActor {
  private var state = IncrementState()

  private def updateState(event: Incremented): Unit = {
    state = state.updated(event)
  }

  override def receiveRecover: Receive = {
    case event:Incremented => updateState(event)
    case SnapshotOffer(_, snapshot: IncrementState) => state = snapshot
  }

  override def receiveCommand: Receive = {
    case Increment(value) =>
      println("incrementing")
      persist(Incremented(value)) {event =>
        println("incremented")
        state = state.updated(event)
      }

    case "snap" => saveSnapshot(state)
    case "print" => println
  }


  override def persistenceId: String = "Counter"
}
```

The read actor:
```scala

object CounterView {
  case object Get
}

class CounterView(val materializer: ActorMaterializer) extends Actor {
  val readJournal = PersistenceQuery(context.system).readJournalFor[JdbcReadJournal](JdbcReadJournal.Identifier)

  val source: Source[EventEnvelope, NotUsed] = readJournal.currentEventsByPersistenceId("Counter", 0, Long.MaxValue)

  implicit val ec = context.dispatcher

  override def receive: Receive = {
    case CounterView.Get =>
      getAllIncrements.pipeTo(sender())
  }

  def getAllIncrements: Future[List[Incremented]] = {
    source.runFold(List.empty[Incremented])((result: List[Incremented], envelope: EventEnvelope) => {
      envelope match {
        case EventEnvelope(offset, persistenceId, sequenceNr, value: Incremented) =>
          println(offset, persistenceId, sequenceNr, value)
          value :: result
      }
    })(materializer)
  }
}
```

And `application.conf`:

```
akka {
  loglevel = DEBUG

  persistence {
    journal {
      plugin = "jdbc-journal"
    }

    snapshot-store {
      plugin = "jdbc-snapshot-store"
    }
  }
}


akka-persistence-jdbc {
  slick {
    driver = "slick.driver.PostgresDriver"
    db {
      host = "localhost"
      host = ${?POSTGRES_HOST}
      port = "5432"
      port = ${?POSTGRES_PORT}
      name = "tinki"

      url = "jdbc:postgresql://"${akka-persistence-jdbc.slick.db.host}":"${akka-persistence-jdbc.slick.db.port}"/"${akka-persistence-jdbc.slick.db.name}
      user = "postgres"
      password = "apass"
      driver = "org.postgresql.Driver"
      keepAliveConnection = off
      numThreads = 2
      queueSize = 100
      connectionTestQuery="select 1"
    }
  }

  tables {
    journal {
      tableName = "journal"
      schemaName = ""
      columnNames {
        persistenceId = "persistence_id"
        sequenceNumber = "sequence_number"
        created = "created"
        tags = "tags"
        message = "message"
      }
    }

    deletedTo {
      tableName = "deleted_to"
      schemaName = ""
      columnNames = {
        persistenceId = "persistence_id"
        deletedTo = "deleted_to"
      }
    }

    snapshot {
      tableName = "snapshot"
      schemaName = ""
      columnNames {
        persistenceId = "persistence_id"
        sequenceNumber = "sequence_number"
        created = "created"
        snapshot = "snapshot"
      }
    }
  }

  query {
    separator = ","
  }
}
```

Am I still doing something wrong here?

**Comment by dnvriend** [comment]
Strange. I have re-created your example in the demo project: https://github.com/dnvriend/demo-akka-persistence-jdbc/blob/master/src/main/scala/com/github/dnvriend/Counter.scala and don't have the problem. Maybe you could take a look? Do you use the latest version of the JDBC plugin? You should use v2.2.8. Launch postgres with `docker-compose up -d` and then launch the sample with `sbt "runMain com.github.dnvriend.Counter"`.

**Comment by elkorn** [comment]
I am also not getting the error with your code.
Investigating further...

**Comment by dnvriend** [comment]
I think the problem lies with the dependencies. You only need akka v2.4.2. Also the akka-stream interface has changed, I think that explains the classcast exception. Just to be sure, please change the dependencies and do a clean in sbt. You will need the following as per [build.sbt](https://github.com/dnvriend/demo-akka-persistence-jdbc/blob/master/build.sbt) of the [demo](https://github.com/dnvriend/demo-akka-persistence-jdbc) project.

```scala
// snip
libraryDependencies ++= {
  val akkaVersion = "2.4.2"
  Seq(
    "com.typesafe.akka" %% "akka-actor" % akkaVersion,
    "com.typesafe.akka" %% "akka-slf4j" % akkaVersion,
    "com.typesafe.akka" %% "akka-stream" % akkaVersion,
    "ch.qos.logback" % "logback-classic" % "1.1.2",
    "com.typesafe.akka" %% "akka-persistence" % akkaVersion,
    "com.typesafe.akka" %% "akka-persistence-query-experimental" % akkaVersion,
    "com.github.dnvriend" %% "akka-persistence-jdbc" % "2.2.8",
    "org.postgresql" % "postgresql" % "9.4-1206-jdbc42",
    "com.typesafe.akka" %% "akka-stream-testkit" % akkaVersion % Test,
    "org.scalatest" %% "scalatest" % "2.2.4" % Test
  )
}
// snip
```

**Comment by elkorn** [comment]
You are correct. Thanks!
