### ISSUE TITLE
Leaking connections

### ISSUE THREAD

**Issue by prettynatty** [dnvriend/akka-persistence-jdbc#44]
After migrating most of business-logic to the akka-persistence with akka-persistence-jdbc as a journal and snapshot-store plugin, application goes down because pool is running out of connections.

Postgres stat shows lots of long-running queries:
![](http://i.imgur.com/WLS4XBj.png)

But in fact it's connections not returned to the pool. When I run this queries manually I get result in ~ 1 millisecond.

I am using slick 3.1.1, HikariCP 2.4.5, PostgreSQL 9.4
I share Database with akka-persistence-jdbc [via jndi](https://github.com/actorapp/actor-platform/blob/master/actor-server/actor-persist/src/main/scala/im/actor/server/db/DbExtension.scala#L72).

**Comment by prettynatty** [comment]
I also get a warning from slick:
```
 WARN  com.zaxxer.hikari.pool.LeakTask    Connection leak detection triggered for connection org.postgresql.jdbc.PgConnection@3a3c8d5d, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at slick.jdbc.DataSourceJdbcDataSource.createConnection(JdbcDataSource.scala:64) ~[com.typesafe.slick.slick_2.11-3.1.1.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415) ~[com.typesafe.slick.slick_2.11-3.1.1.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414) ~[com.typesafe.slick.slick_2.11-3.1.1.jar:na]
	at slick.jdbc.JdbcBackend$BaseSession.startInTransaction(JdbcBackend.scala:437) ~[com.typesafe.slick.slick_2.11-3.1.1.jar:na]
	at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:41) ~[com.typesafe.slick.slick_2.11-3.1.1.jar:na]
	at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:38) ~[com.typesafe.slick.slick_2.11-3.1.1.jar:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237) ~[com.typesafe.slick.slick_2.11-3.1.1.jar:na]
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237) ~[com.typesafe.slick.slick_2.11-3.1.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_92]
```

**Comment by dnvriend** [comment]
I'm kinda sick right now, but please try again with HikariCP 2.3.13 as it's the one Slick is compiled against. Maybe you are having an API/settings incompatibility.

**Comment by dnvriend** [comment]
Please see the Build.scala from [slick](https://github.com/slick/slick/blob/master/project/Build.scala). To be exact, please try "com.zaxxer" % "HikariCP-java6" % "2.3.13".

**Comment by dnvriend** [comment]
The version from akka-persistence-jdbc is using "com.zaxxer" % "HikariCP-java6" % "2.3.7", but if the devs are using the version numbers correctly (fingers crossed) 2.3.15 should be compatible.

**Comment by prettynatty** [comment]
Get well soon!
I downgraded HikariCP to ` "com.zaxxer" % "HikariCP-java6" % "2.3.7"` but still see the same problem.

**Comment by dnvriend** [comment]
Rats, when I'm feeling better I'll take a look.

**Comment by prettynatty** [comment]
May it happen because [I create `AsyncExecutor`](https://github.com/actorapp/actor-platform/blob/341f0f321a428fa1ba5a156fd7841a7a3a6d6cf3/actor-server/actor-persist/src/main/scala/im/actor/server/db/DbExtension.scala#L71), share datasource with `akka-persistence-jdbc`, then `SlickDatabase` creates its own `AsyncExecutor` too?

**Comment by prettynatty** [comment]
Changed my code to reuse `SlickDatabase`'s db (and `AsyncExecutor` too), didn't help.

**Comment by prettynatty** [comment]
To prevent queue overflow I created [a branch](https://github.com/prettynatty/akka-persistence-jdbc/tree/jndi-db) with an ability to share Database instance, not only Datasource (should I make a PR? It's useful to share AsyncExecutor and its settings).

No more queue errors but still all connections are busy for minutes.
