### ISSUE TITLE
Cryptic error message

### ISSUE THREAD

**Issue by divijan** [dnvriend/akka-persistence-jdbc#60]
I've recently updated to 2.6.1 and I'm getting stack traces like this:
```
2016-07-26 12:29:33,108 [default-akka.actor.default-dispatcher-7] [ERROR] [com.optrak.opkakka.ddd.persistence.InitialisingPersistor] Failed to persist event type [com.optrak.opkakka.ddd.test.individual.Orders$QuantityUpdated] with sequence number [4] for persistenceId [382a7739-e7da-4d85-b453-509fdfba577f-orders-1].
scala.MatchError: Vector(Success(JournalRow(-9223372036854775808,false,382a7739-e7da-4d85-b453-509fdfba577f-orders-1,4,[B@36fb4165,None))) (of class scala.collection.immutable.Vector)
	at akka.persistence.jdbc.util.TrySeq$.sequence(TrySeq.scala:31)
	at akka.persistence.jdbc.serialization.FlowPersistentReprSerializer$class.akka$persistence$jdbc$serialization$FlowPersistentReprSerializer$class$$$anonfun$3(PersistentReprSerializer.scala:52)
	at akka.persistence.jdbc.serialization.FlowPersistentReprSerializer$class$$Lambda$56/1661213932.apply(Unknown Source)
	at akka.stream.impl.fusing.Map.onPush(Ops.scala:29)
	at akka.stream.impl.fusing.Map.onPush(Ops.scala:28)
	at akka.stream.stage.AbstractStage$PushPullGraphLogic$$anon$1.onPush(Stage.scala:55)
	at akka.stream.impl.fusing.GraphInterpreter.processElement$1(GraphInterpreter.scala:590)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:601)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:542)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:381)
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:538)
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:586)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:489)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) 
```
The code doesn't look right to me: you are matching a Seq against List patterns here https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/util/TrySeq.scala#L22

**Comment by dnvriend** [comment]
Ouch, that is not good. Strange the test is green though. I will look into it. Thanks for reporting!

**Comment by divijan** [comment]
Could it be the problem on my part?

**Comment by dnvriend** [comment]
I don't know how it could...

**Comment by dnvriend** [comment]
I have released v2.6.2 that contains a refactored TrySeq. Please try it out and let me know!

**Comment by divijan** [comment]
Wow, that was some heavy refactoring with akka streams. It works now, sweet! Thanks

**Comment by dnvriend** [comment]
No problem 😀😀 .
